export enum PaymentStatus {
    AUTHORIZED = 'AUTHORIZED',
    WAITING_AUTHORIZATION = 'WAITING_AUTHORIZATION',
    WAITING_PAYMENT = 'WAITING_PAYMENT',
    PAID = 'PAID',
    WAITING_REFUND = 'WAITING_REFUND',
    PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
    REFUNDED = 'REFUNDED',
    REFUSED = 'REFUSED',
}

export enum PaymentStatusNew {
    AUTHORIZED = 'AUTHORIZED',
    WAITING_AUTHORIZATION = 'WAITING_AUTHORIZATION',
    WAITING_PAYMENT = 'WAITING_PAYMENT',
    PAID = 'PAID',
    PARTIALLY_PAID = 'PARTIALLY_PAID',
    OVER_PAID = 'OVER_PAID',
    REFUSED = 'REFUSED',
    WAITING_REFUND = 'WAITING_REFUND',
    PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
    REFUNDED = 'REFUNDED',
}
